### ISSUE TITLE
Bug & Fix for modal closing (data-dismiss)

### ISSUE THREAD

**Issue by Nyan11** [astares/Seaside-Bootstrap5#8]
# The bug:

There is a bug with the modal.

Pharo code:
```st
renderContentOn: html
  html modal
    id: 'testModal';
    fade;
    with: [ html
      modalDialog beCentered; with: [ html
        modalContent: [ html
          modalHeader: [ html modalTitle
            level5;
            with: 'Modal Title'.
            html modalCloseButton dataDismiss: 'modal' ] ] ] ]
```

I added dataDismiss to the button for closing the modal. But when i click close on the website, it doesn't work.

The HTML code generate for the close is button:

```html
<button class="close" data-dismiss="modal">×</button>
```

For the modal to close it should be:

```html
<button class="close" data-bs-dismiss="modal">×</button>
```

# A possible fix:

In Bootstrap5-Core > SBSButtonTag  > dataDismiss

old
```st
{ #category : #options }
SBSButtonTag >> dataDismiss: aString [

	self attributeAt: 'data-dismiss' put: aString
]
```

new
```st
{ #category : #options }
SBSButtonTag >> dataDismiss: aString [

	self attributeAt: 'data-bs-dismiss' put: aString
]
```

**Comment by Nyan11** [comment]
Ps: you can test it by modifying the example in: Bootstrap5-Example> SBSModalExample> renderExampleOn:

**Comment by astares** [comment]
@Nyan11 Thanks. Please provide code fixes as PR - then it is easy to double check and merge

**Comment by astares** [comment]
@Nyan11 I fixed it in latest commit on master
